##
## MIT License
##
## Copyright (c) 2020-2022 NVIDIA CORPORATION.
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.##
robot: 'Kinova Gen3'

collision_spheres:
  base_link:
      - "center": [0.0, 0.0, 0.0]
        "radius": 0.05
      - "center": [0.0, 0.0, 0.1]
        "radius": 0.05
  shoulder_link:
      - "center": [0.0, 0.0, -0.1]
        "radius": 0.06
      - "center": [0.0, 0.0, -0.15]
        "radius": 0.05
  half_arm_1_link:
      - "center": [0.0, -0.0, 0.0]
        "radius": 0.055
      - "center": [0.0, -0.07, 0.0]
        "radius": 0.055
      - "center": [0.0, -0.15,0.0]
        "radius": 0.055
  half_arm_2_link:
      - "center": [0.0, -0.0, 0.0]
        "radius": 0.055
      - "center": [0.0, -0.0, -0.07]
        "radius": 0.055
      - "center": [0.0, -0.0,-0.15]
        "radius": 0.055
      - "center": [0.0, -0.0,-0.21]
        "radius": 0.055
  forearm_link:
      - "center": [0.0, -0.0, 0.0]
        "radius": 0.055
      - "center": [0.0, -0.07, -0.0]
        "radius": 0.055
      - "center": [0.0, -0.17,-0.0]
        "radius": 0.055
  spherical_wrist_1_link:
      - "center": [0.0, -0.0, 0.0]
        "radius": 0.055
      - "center": [0.0, -0.0, -0.085]
        "radius": 0.055
  spherical_wrist_2_link:
      - "center": [0.0, -0.0, 0.0]
        "radius": 0.05
      - "center": [0.0, -0.085, -0.0]
        "radius": 0.05
  bracelet_link:
      - "center": [0.0, -0.0, -0.05]
        "radius": 0.04
